### PR TITLE
Allow capitals in password and fix password generation

### PR DESCRIPTION
**Pull request by Tymewalk**
Many sites will require capitals in their passwords, so you have an option to toggle capitals in the password.
Also, apparently moving the entire script to a separate function broke the script (at least for me on Firefox). *facepalm*
To fix it, I put only the generation of the password in a function and set the innerHTML in the "onclick".

Let me know if there's any problems, this appears to work for me on Firefox.

### CODE REVIEW

**Comment by DrKat123** [comment]
Okay

**Comment by DrKat123** [comment]
Anyway i'm gonna add you as a contributor to this repo

**Comment by Tymewalk** [comment]
@DrKat123 Thanks! I'll see if there's anything else I can do, I think there's an easier way to make the words use capital letters, and a checkbox would probably be better than a button to toggle.

**Comment by DrKat123** [comment]
Yeah...
I'll update the main site's HTML next Sunday

**Pull request merged**
